### HOME ROUTES
GET http://localhost:3000/

### GET REQUEST ALL FOOD
GET http://localhost:3000/foods

### GET REQUEST FOOD W/PARAMETER

GET http://localhost:3000/foods?mealType=breakfast

### POST REQUEST ADDING FOOD

POST http://localhost:3000/foods
Content-Type: application/json

{
  "foodName": "Hamburger",
  "calories": 500,
  "mealType": "dinner"
}